background = #020908
background-opacity = 1.0
foreground = #cffff0
cursor-color = #e7fff8
selection-background = #103e34
selection-foreground = #e7fff8

palette = 0=#020908
palette = 1=#ff718f
palette = 2=#63efba
palette = 3=#d7f58a
palette = 4=#52cdb5
palette = 5=#8bd6c5
palette = 6=#7ffff0
palette = 7=#cffff0
palette = 8=#174a40
palette = 9=#ff9caf
palette = 10=#a5ffd8
palette = 11=#ebffad
palette = 12=#8fffe3
palette = 13=#b9f5e7
palette = 14=#cafff3
palette = 15=#e7fff8
